# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170417_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Image',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u8bfe\u7a0b\u63cf\u8ff0\u56fe'),
        ),
    ]
