# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.TextField(default='', max_length=300, verbose_name='\u8bb2\u5e08\u8bf4'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.TextField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
